ALTER TABLE "trench_pairs" ADD COLUMN "mcap" TEXT NOT NULL DEFAULT '0';
ALTER TABLE "trench_pairs" ADD COLUMN "athMcap" TEXT NOT NULL DEFAULT '0';
ALTER TABLE "trench_pairs" ADD COLUMN "volume" TEXT NOT NULL DEFAULT '0';
ALTER TABLE "trench_pairs" ADD COLUMN "taxPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "trench_pairs" ADD COLUMN "creatorTaxBps" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "trench_pairs" ADD COLUMN "txns" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "trench_pairs" ADD COLUMN "holders" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "trench_pairs" ADD COLUMN "bundlers" INTEGER NOT NULL DEFAULT 0;
